//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Narzedzia_IP_2.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateAuto
        {
            get
            {
                return ((bool)(this["UpdateAuto"]));
            }
            set
            {
                this["UpdateAuto"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UpdateSkipped
        {
            get
            {
                return ((string)(this["UpdateSkipped"]));
            }
            set
            {
                this["UpdateSkipped"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150.150.222.20")]
        public string DhcpServer
        {
            get
            {
                return ((string)(this["DhcpServer"]));
            }
            set
            {
                this["DhcpServer"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.202.130.0")]
        public string AclSubnet1Net
        {
            get
            {
                return ((string)(this["AclSubnet1Net"]));
            }
            set
            {
                this["AclSubnet1Net"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255.255.254.0")]
        public string AclSubnet1Mask
        {
            get
            {
                return ((string)(this["AclSubnet1Mask"]));
            }
            set
            {
                this["AclSubnet1Mask"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.207.156.0")]
        public string AclSubnet2Net
        {
            get
            {
                return ((string)(this["AclSubnet2Net"]));
            }
            set
            {
                this["AclSubnet2Net"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255.255.254.0")]
        public string AclSubnet2Mask
        {
            get
            {
                return ((string)(this["AclSubnet2Mask"]));
            }
            set
            {
                this["AclSubnet2Mask"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ACL-BCS2-IN-VLAN130")]
        public string AclIn1
        {
            get
            {
                return ((string)(this["AclIn1"]));
            }
            set
            {
                this["AclIn1"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ACL-BCS2-OUT-VLAN130")]
        public string AclOut1
        {
            get
            {
                return ((string)(this["AclOut1"]));
            }
            set
            {
                this["AclOut1"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ACL-BCS-IN")]
        public string AclIn2
        {
            get
            {
                return ((string)(this["AclIn2"]));
            }
            set
            {
                this["AclIn2"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ACL-BCS-OUT")]
        public string AclOut2
        {
            get
            {
                return ((string)(this["AclOut2"]));
            }
            set
            {
                this["AclOut2"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("540")]
        public int AclSeqIn
        {
            get
            {
                return ((int)(this["AclSeqIn"]));
            }
            set
            {
                this["AclSeqIn"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("530")]
        public int AclSeqOut
        {
            get
            {
                return ((int)(this["AclSeqOut"]));
            }
            set
            {
                this["AclSeqOut"] = value;
            }
        }
    }
}
